---
- name: Install "Minimal Install" package group
  yum: 
    name: "@Minimal Install"
    state: latest

- name: Install base soft
  yum: name={{ item }} state=present
  with_items: "{{ packages }}"
