zbx_agent_Version: "3.2.6"
zbx_repo_centos6: http://repo.zabbix.com/zabbix/3.2/rhel/6/x86_64/zabbix-release-3.2-1.el6.noarch.rpm 
zbx_repo_centos7: http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm

# General Zabbix Agent Parameters

zbx_agent_Pid: "/var/run/zabbix/zabbix_agentd.pid"      # Location of Agent PID File
zbx_agent_Log: "/var/log/zabbix/zabbix_agentd.log"      # Location of Agent Log File
zbx_agent_LogSize: 0                                    # Log File Size In MB ( 0 = disabled Log Rotation )
zbx_agent_Debug: 3                                      # Debug Level (0 = no debug, 1=critical, 2=error info, 3=warnings, 4=debug )
zbx_agent_SourceIp:                                     # Source IP address for outgoing connections.
zbx_agent_Remote: 0                                     # Enable remote commands ( 0=disabled, 1=enabled)
zbx_agent_LogRemote: 0                                  # Log Remote Commands ( Enable logging of executed commands )
zbx_agent_Port: 10050                                   # Zabbix Agent Listen Port (if changed also alter tasks/iptables.yml
zbx_agent_StartAgents: 3                                # Number of Pre-Forked Instances of zabbix_agentd
zbx_agent_HostName:                                     # Put the hostname if not filled in name of the machine is used
zbx_agent_HostMeta:                                     # Optional parameter that defines host metadata.
zbx_agent_HostMetaItem:                                 # Optional parameter that defines an item used for getting host metadata
zbx_agent_RefreshActiveChecks: 120                      # How often list of active checks is refreshed, in seconds.
zbx_agent_Buffer: 5                                     # Do not keep data longer then N seconds in buffer.
zbx_agent_BufferSize: 100                               # Maximum number of values in a memory buffer
zbx_agent_MaxLinesSecond: 100                           # Maximum number of new lines the agent will send per second to Zabbix Server

#======Zabbix API============
#==Switch==
zbx_create_hostgroup: present                           # or absent | present
zbx_create_host: present                                # or absent
status: "enabled"                                       # Status of the host enabled or disabled
state: "present"
zbx_api_create_hostgroup: True
#==API==
#nginx_daemon: "127.0.0.1:80"
server_url: http://{{ nginx_daemon }}/zabbix
zbx_api_user: Admin
zbx_api_pass: zabbix
zbx_link_templates:
                 - "Template DCITS OS Linux"
                 - "Template App Zabbix Agent"
agent_interfaces:
  - type: 1                                             #1-agent; 2-SNMP; 3-IPMI; 4-JMX.
    main: 1
    useip: 1                                            #0-DNS; 1-IP address
    ip: "{{ agent_ip }}"                                              #本机IP地址
    dns: "{{ hostname }}"                               #本机DNS主机名
    port: 10050  
zbx_host_groups:
  - ansible-test3
