---
- name: Download Centos repo from aliyun
  get_url:
    url: http://mirrors.aliyun.com/repo/Centos-7.repo 
    dest: /etc/yum.repos.d/Centos-7.repo
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"


- name: Download EPEL repo from aliyun
  get_url:
    url: http://mirrors.aliyun.com/repo/epel-7.repo 
    dest: /etc/yum.repos.d/epel-7.repo 
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7"


- name: Download Centos repo from aliyun
  get_url:
    url: http://mirrors.aliyun.com/repo/Centos-6.repo
    dest: /etc/yum.repos.d/Centos-6.repo
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"


- name: Download EPEL repo from aliyun
  get_url:
    url: http://mirrors.aliyun.com/repo/epel-6.repo
    dest: /etc/yum.repos.d/epel-6.repo
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "6"
