hostname: agent4

#=======zabbix-api=============
agent_ip: "{{ ansible_default_ipv4.address }}"
##zbx_host_groups:
##              - "vpn1"
##zbx_link_templates:
##                 - "Template DCITS OS Linux"
#
#

